package:
  name: gs_ddrad2015
  version: "1.0.1"

source:
  # git_url: https://github.com/CacconeLabYale/gloria_soria_ddRAD_2015.git
  # git_rev: v1.0.1
  path: ../

#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    - gs_ddRAD2015=gs_ddRAD2015.scripts.main:cli

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 2

requirements:
  build:
    - python
    - setuptools
    - click
    - jupyter
    - ipython
    - matplotlib
    - munch
    - seaborn
    - ggplot
    - numpy
    - pandas
    - pyyaml
    - pytables
    - scipy
    - statsmodels
    - ipdb
    - pymc==2.3.5
    - pybedtools
    - tabulate
    - scikits.bootstrap
    - spartan-bio


  run:
    - python
    - click
    - jupyter
    - ipython
    - matplotlib
    - munch
    - seaborn
    - ggplot
    - numpy
    - pandas
    - pyyaml
    - pytables
    - scipy
    - statsmodels
    - ipdb
    - pymc==2.3.5
    - pybedtools
    - tabulate
    - scikits.bootstrap
    - spartan-bio


test:
  # Python imports
  imports:
      - gs_ddRAD2015

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - gs_ddRAD2015 --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/CacconeLabYale/gloria_soria_ddRAD_2015.git
  license: MIT
  summary: 'code in support of the tsetse ddRAD paper'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
